pipeline {
    agent any

    stages {
        stage('Install Frontend Dependencies') {
            steps {
                dir('frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    bat 'npm run build'
                }
            }
        }
    }

    post {
        success {
            bat '''
                if not exist "C:\\JenkinsFeedback" mkdir "C:\\JenkinsFeedback"

                echo.>> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Number: %BUILD_NUMBER% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Status: SUCCESS >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Project: SkillSwap >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Job Name: %JOB_NAME% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
            '''
        }

        failure {
            bat '''
                if not exist "C:\\JenkinsFeedback" mkdir "C:\\JenkinsFeedback"

                echo.>> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Number: %BUILD_NUMBER% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Status: FAILURE >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Project: SkillSwap >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Job Name: %JOB_NAME% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
            '''
        }
    }
}